behaviors:
  BlockPlayer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 256000
      learning_rate: 2.0e-4
      beta: 2.5e-2
      epsilon: 0.1
      lambd: 0.90
      num_epoch: 10
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #gail:
        #strength: 1.0
        #demo_path: PlayingAgent1/PlayerTraining9/BCAgentRunLatest.demo
    #behavioral_cloning:
      #strength: 1.0
      #demo_path: PlayingAgent1/PlayerTraining9/BCAgentRunLatest.demo




    max_steps: 200000000
    time_horizon: 256
    summary_freq: 10000

